export const DELETEHEATER_REQUEST = 'DELETEHEATER/DELETEHEATER_REQUEST';
export const DELETEHEATER_SUCCESS = 'DELETEHEATER/DELETEHEATER_SUCCESS';
export const DELETEHEATER_FAILURE = 'DELETEHEATER/DELETEHEATER_FAILURE';
