export const CHANGEHEATER_REQUEST = 'CHANGEHEATER/CHANGEHEATER_REQUEST';
export const CHANGEHEATER_SUCCESS = 'CHANGEHEATER/CHANGEHEATER_SUCCESS';
export const CHANGEHEATER_FAILURE = 'CHANGEHEATER/CHANGEHEATER_FAILURE';
