export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD/CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD/CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILURE = 'CHANGEPASSWORD/CHANGEPASSWORD_FAILURE';
