export const GETCURRENTTEMP_REQUEST = 'GETCURRENTTEMP/GETCURRENTTEMP_REQUEST';
export const GETCURRENTTEMP_SUCCESS = 'GETCURRENTTEMP/GETCURRENTTEMP_SUCCESS';
export const GETCURRENTTEMP_FAILURE = 'GETCURRENTTEMP/GETCURRENTTEMP_FAILURE';
