export const STATUSDATA_REQUEST = 'STATUSDATA/STATUSDATA_REQUEST';
export const STATUSDATA_SUCCESS = 'STATUSDATA/STATUSDATA_SUCCESS';
export const STATUSDATA_FAILURE = 'STATUSDATA/STATUSDATA_FAILURE';
