export const INSTALLERINFO_REQUEST = 'INSTALLERINFO/INSTALLERINFO_REQUEST';
export const INSTALLERINFO_SUCCESS = 'INSTALLERINFO/INSTALLERINFO_SUCCESS';
export const INSTALLERINFO_FAILURE = 'INSTALLERINFO/INSTALLERINFO_FAILURE';
