export const EDITPROFILE_REQUEST = 'EDITPROFILE/EDITPROFILE_REQUEST';
export const EDITPROFILE_SUCCESS = 'EDITPROFILE/EDITPROFILE_SUCCESS';
export const EDITPROFILE_FAILURE = 'EDITPROFILE/EDITPROFILE_FAILURE';
