export const GETERRORINFO_REQUEST = 'GETERRORINFO/GETERRORINFO_REQUEST';
export const GETERRORINFO_SUCCESS = 'GETERRORINFO/GETERRORINFO_SUCCESS';
export const GETERRORINFO_FAILURE = 'GETERRORINFO/GETERRORINFO_FAILURE';
