export const GET_TIMEZONE_REQUEST = 'GET_TIMEZONE/OFF/GET_TIMEZONE_REQUEST';
export const GET_TIMEZONE_SUCCESS = 'GET_TIMEZONE/OFF/GET_TIMEZONE_SUCCESS';
export const GET_TIMEZONE_FAILURE = 'GET_TIMEZONE/OFF/GET_TIMEZONE_FAILURE';
