export default {
  enterFullName: 'Please enter fullname.',
  enterEmail: 'Please enter email.',
  enterPassword: 'Please enter password.',
  enterConfirmPassword: 'Please enter confirm password.',
  passwordNotMatch: 'Password and Confirm Password not matched.',
  enterValidEmail: 'Please enter valid email.',
  networkError:
    'It seems some problem in network connectivity. Please try again after some time.',
  txtRegister: 'Register',
  AlreadyPairedMsg: 'This adapter has already been paired \nwith another smartphone ',
  txtYouAgree: 'you agree to the ',
  txtTermsAndCondition: 'Terms and Conditions ',
  txtCopyright: 'Copyright © 2017, NORITZ AMERICA CORP. ',
  txtAllRights: 'All Rights Reserved',
  commonErrorMessage: 'Something went wrong! Please try again later.',
  txtByclicking: 'By clicking ',
  ManuallyChhoseHeater: 'Manually choose your heater',
  txtGoToSettings: '- Go to Phone Settings - Wifi Setup.\n- Look for Network named NAW',
  txtConectAndCome: '\n- Connect and come back to the App.',
  txtStatus: 'Status',
  txtConnected: 'Connected',
  txtErrorInfo: 'Error Info',
  txtBurnTime: 'Burn Time',
  txtPluginTime: 'Total Plug In Time',
  txtIgnitionTime: 'Ignition Time',
  txtTotalGasUsage: 'Total Gas Usage',
  txtScaleBuildDetection: 'Scale Build Up Detection',
  txtFlowRate: 'Flow Rate',
  txtInletTemp: 'Inlet Temperature',
  txtLastDescaleDate: 'Last Descale Date',
  txtRefresh: 'Refresh',
  txtSystemTotalUnits: 'Syatem total units',
  txtSystemMode: 'System Mode',
  txtOnline: 'Online',
  txtActive: 'Active',
  txtUnit: 'Unit',
  txtPumpOperationalPeriod: 'Pump operational period',
  txtPumpRecirculationFlowRate: 'Pump recirculation flow rate',
  txtOutdoorTemp: 'OutdoorTemperature',
  txtPressAgainToExit: 'Press again to exit',
  txtAddHeater: 'Add Heater',
  txtEditHeaterDetails: 'Edit Heater Details',
  txtEditProfile: 'Edit Profile',
  txtHelpfulTips: 'Helpful Tips',
  txtWirelessLanSetup: 'Wireless Lan Setup',
  txtSelectTimezone: 'Select Timezone',
  txtTermsOfUse: 'Terms of use',
  txtLogout: 'Logout',
  txtSettings: 'Settings',
  txtSystemStatus: 'System Status',
  txtEvent: 'Events',
  txtSelect: 'Select',
  txtPoerOnOff: 'Power On/Off',
  txtRecirculation: 'Recirculation',
  txtOnDemand: 'On demand',
  txtTimerMode: 'Timer Mode',
  txtAuto: 'Auto',
  txtPleaseWait: 'Please wait',
  txtWaitMessage: 'This process can take up to 30 seconds.',
  txtCancel: 'Cancel',
  txtRecirculationTimer: 'Recirculation Timer',
  txtOnOffTimer: 'On/Off Timer',
  txtSwitchMode: 'Switch Mode',
  switchModeDesc1: 'If you set Timer, ”Auto” changes into ”Manual”.',
  switchModeDesc2: 'To switch back from “Manual” to ”Auto”, you need to set up on the heater.',
  txtEnterPassword: 'Enter password to continue',
  txtAccept: 'Accept',
  txtSetTempandPower: 'Set Temperature & Power',
  txtProceedAtRisk: 'Proceed at your own risk.',
  txtEnterPasswrd: 'Enter password',
  txtPumpOffTime: 'Pump off Time',
  timerPopupDesc: 'If you set Timer, ”Auto” changes into ”Manual”.\nTo switch back from “Manual” to ”Auto”, you need to set up on the heater.',
  txtSetTemp: 'Set Temperature',
  setTempForHeating: 'Set Temperature (for Heating)',
  txtControl: 'Control',
  txtUsageData: 'Usage Data',
  powerAlertDesc: 'Turning off your Water Heater will clear the current error code, would you like to proceed?',
  txtOK: 'OK',
  serverError: 'Server is not responding. Please try again.',
  TempWarningDesc: 'Setting the temperature above 120° can result in severe burn. Proceed at your own risk.',
  invalidPassword: 'Invalid password.',
  txtNotConnected: 'Not Connected',
  logoutWarning: 'Are you sure you want to logout?',
  txtPressWPSButton: '- Press the WPS button on your router.',
  txtPressWPSButtonHeater: '- Press the WPS button on your heater.',
  txtContinue: 'Continue',
  txtWaitingForHeater: 'Waiting for heater to come online',
  txtPleaseReconnect: 'Please reconnect your phone to your Home Wireless Router if it does not automatically connect.',
  txtHeaterOnline: 'Heater Online',
  txtFailedToConnect: 'Failed to connect to network',
  descCongratulations: 'Congratulations! Your heater is now online! Please tap the “Done” button to continue.',
  descFail: 'Please tap the “Retry” button to go through \nthe steps again \nIf this issue persists, please contact Noritz \nSupport at (866)766-7489',
  descUnfortunatly: 'Unfortunately, Nortiz Connect was not\nable to connect to your heater. It can\nhappen for various reasons.',
  txtAlreadyPairedDesc: 'Please tap the “Retry” button to go through the steps again.',
  txtWaitForFewSeconds: 'Wait for few seconds, and check if unit,',
  txtLEDisON: 'router, and server LEDs are on',
  txtLightsAreOn: 'Lights are on. Continue',
  txtIfLightsAreOn: 'If the lights are not on, it can mean',
  txtIfLightsAreOn2: 'incorrect wifi network and/or password,',
  txtIfLightsAreOn3: 'or a step was missed during the process.',
  txtStartOver: 'Start Over',
  txtIfTheIssuePersist: 'If the issue persists, please contact Noritz',
  txtSupportAt: 'Support at (866) 766-7489',
  alreadyPairedContactMessage: 'If this issue persists, please contact Noritz Support at (866)766-7489',
  txtYesItIsConnected: "Yes, it is connected. Let's Start",
  txtTheUnitLightIsON: 'The Unit Light is on Now.',
  txtNetworkNotFound: "Couldn't find the network",
  txtNetworkConnected: 'Network Connected. Continue',
  alerttxtGoToSettings: 'Go to Settings',
  wifiSetupDesc1: 'Before starting the setup, please make\nsure your wifi adapter is connected to the\nheater.',
  wifiSetupDesc2: 'Press and Hold the AP Button for 3\nSeconds. At this point, the unit light\nshould turn on.',
  wifiSetupDesc3: '- Go to Phone Settings - Wifi Setup.\n- Look for Network named NAWxxxx.\n- Connect and come back to the App.',
  txtPleaseFillAllFields: 'Please fill all mandatory fields.',
  txtCustomerInfo: 'Customer Information',
  txtFirstName: 'First Name*',
  txtLastName: 'Last Name*',
  txtAddress: 'Address*',
  txtCity: 'City*',
  txtStates: 'State*',
  txtZipCode: 'Zip code*',
  txtPhone: 'Phone*',
  txtFax: 'Fax',
  txtEmail: 'Email*',
  txtInstallationType: 'Installation Type*',
  txtResidenceType: 'Residence Type',
  txtInstallationCompany: 'Installation Company Information',
  txtCompanyName: 'Company Name',
  txtInstallerName: 'Installer Name',
  txtLicenceNumber: 'License Number',
  txtPlaceOfPurchase: 'Place of Purchase',
  txtModelNumber: 'Model Number*',
  txtGasType: 'Gas Type*',
  txtDateOfInstall: 'Date of Install*',
  txtSelectDate: 'select date',
  txtSubmitWarranty: 'Submit Warranty',
  txtDayLightSave: 'Automatically manage DST',
  txtAcceptTerms: 'Accept Terms of use',
  txtSetupUsingWPS: 'Setup using WPS',
  WPSDesc: 'If your router supports Wifi protected\nsetup (WPS), find the button on your\nrouter, and tap here to continue the\nsetup process.',
  txtManualRouterSetup: 'Manual Router Setup',
  manualSetupDesc: "If you are not sure, or your router\ndoesn't support WPS, you can configure\nit manually by entering password. Please tap here to continue.",
  txtFullName: 'Full Name',
  txtfldEmail: 'Email',
  txtfldPassword: 'Password',
  txtfldConfirmPassword: 'Confirm Password',
  txtEnterWifiPassword: 'Enter your Wi-Fi password',
  txtConnect: 'Connect',
  txtSelectWirelessNetwork: 'Select your HomeWireless Router',
  txtSSID: 'SSID',
  txtSignal: 'Signal',
  txtWifiPassword: 'Wifi Password',
  txtRetry: 'Retry',
  txtSearchingLocalNetwork: 'Searching for Local Networks',
  txtRememberme: 'Remember Me',
  txtSignin: 'Sign in',
  txtForgotPassword: 'Forgot your password?',
  txtOR: 'OR',
  txtSigninWithFacebook: 'Sign in with Facebook',
  txtSigninWithTwitter: 'Sign in with Twitter',
  txtDontHaveAccount: "Don't have account?",
  txtSignUp: ' Sign up',


  msgLocationPermissionDenid: 'Location permission denied. This app needs location permission to scan wifi networks.',
  msgLocationPermissionRequiredTitle: 'Location permission is required for WiFi connections',
  msgLocationPermissionRequired: 'This app needs location permission as this is required  ' + 'to scan for wifi networks.',
  msgHeaterNotResponding: 'Heater is not responding, Please try again.',
  msgPleaseSelectWifi: 'Please select your home wireless router.',
  msgHeaterNotConnected: 'Your device is not connected to the heater.',
  correctSchedule: 'This schedule seems to be in conflict with an existing schedule, please change this or update the existing one to avoid conflict.'
};
