export const UPDATE_METADATA_REQUEST = 'UPDATE_METADATA/METADATA_REQUEST';
export const UPDATE_METADATA_SUCCESS = 'UPDATE_METADATA/METADATA_SUCCESS';
export const UPDATE_METADATA_FAILURE = 'UPDATE_METADATA/METADATA_FAILURE';
