export const HEATERON_OFF_REQUEST = 'HEATERON/OFF/HEATERON/OFF_REQUEST';
export const HEATERON_OFF_SUCCESS = 'HEATERON/OFF/HEATERON/OFF_SUCCESS';
export const HEATERON_OFF_FAILURE = 'HEATERON/OFF/HEATERON/OFF_FAILURE';
