export const VALIDATE_HEATER_REQUEST = 'VALIDATE_HEATER/VALIDATE_HEATER_REQUEST';
export const VALIDATE_HEATER_SUCCESS = 'VALIDATE_HEATER/VALIDATE_HEATER_SUCCESS';
export const VALIDATE_HEATER_FAILURE = 'VALIDATE_HEATER/VALIDATE_HEATER_FAILURE';
