export const EDITHEATER_REQUEST = 'EDITHEATER/EDITHEATER_REQUEST';
export const EDITHEATER_SUCCESS = 'EDITHEATER/EDITHEATER_SUCCESS';
export const EDITHEATER_FAILURE = 'EDITHEATER/EDITHEATER_FAILURE';
