export const CHANGETEMP_REQUEST = 'CHANGETEMP/CHANGETEMP_REQUEST';
export const CHANGETEMP_SUCCESS = 'CHANGETEMP/CHANGETEMP_SUCCESS';
export const CHANGETEMP_FAILURE = 'CHANGETEMP/CHANGETEMP_FAILURE';
