import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import Fonts from '../../services/Fonts';
import {getColors} from '../../services/Color';

const styles = {
  pageContainer: {
    flex: 1,
  },
  btnSystemStatusContainer: {
    marginTop: 10,
    width: wp('42.5%'),
    marginLeft: 0,
    borderColor: getColors().redColor,
    borderWidth: 1,
  },
  btnUnitStatusStyle: {
    marginTop: 10,
    width: wp('42.5%'),
    marginLeft: 0,
    borderColor: getColors().redColor,
    borderWidth: 1,
  },
  containerTxtAddHeater: {flex: 1, justifyContent: 'flex-end'},
  btnRefreshNew: {marginTop: 10, width: wp('42.5%')},
  setTitleWidth: {width: wp('%33')},
  homeBGImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    left: 0,
    top: 0,
  },
  iconsSettingsTab: {
    width: wp('9.66%'),
    height: wp('9.66%'),
  },
  txtSettingsTab: {
    fontSize: wp('5%'),
    color: 'white',
    fontFamily: Fonts.oxygenRegular,
    marginHorizontal: 20,
  },
  xAxisStyle: {
    marginLeft: wp('18%'),
    height: 50,
    marginRight: 20,
    marginTop: 5,
  },
  yAxisStyle: {
    width: '15%',
  },
  chartBG: {
    width: 'auto',
    height: hp('15%'),
    marginTop: 20,
    marginHorizontal: 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  gestureViewStyle: {width: '100%', height: 'auto'},
  statusTabTxtStyle: {flex: 1, fontSize: wp('4%')},
  txtStatusTitle: {width: wp('33%'), fontSize: wp('4%')},
  txtEventStyle: {
    width: hp('15%'),
    position: 'absolute',
    left: -hp('7.5%'),
    top: hp('7%'),
    backgroundColor: 'transparent',
    transform: [{rotate: '-90deg'}],
  },
  areaChartStyle: {
    width: '85%',
    height: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#9b9b9b',
    backgroundColor: 'transparenr',
  },
  innerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  setTemperatureImage: {
    width: wp('70%'),
    height: wp('7%'),
    marginTop: 0,
  },
  cellIcon: {
    width: wp('7%'),
    height: wp('7%'),
    marginLeft: 20,
  },
  txtTemperature: {
    fontSize: wp('25%'),
    color: 'white',
    fontFamily: Fonts.oxygenLight,
    marginLeft: 20,
  },
  txtDegree: {
    fontSize: 80,
    color: 'white',
    fontFamily: Fonts.oxygenLight,
  },
  titleTemperaturePopup: {
    fontFamily: Fonts.oxygenBold,
    fontSize: wp('5%'),
    marginTop: 10,
    marginHorizontal: 10,
  },
  contentTemperaturePopup: {
    fontFamily: Fonts.oxygenLight,
    fontSize: wp('4%'),
    marginTop: 10,
    marginHorizontal: 10,
    lineHeight: wp('5%'),
    lineSpacing: 5,
  },
  closeTemperaturePopup: {
    fontFamily: Fonts.oxygenBold,
    fontSize: wp('5%'),
    position: 'absolute',
    width: 80,
    height: 40,
    right: 10,
    bottom: 0,
    textAlign: 'right',
  },
  bottomTabView: {
    width: '100%',
    height: hp('7.04%'),
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
  },
  tabBarSeperator: {
    height: '70%',
    width: 0.5,
    backgroundColor: '#86929D',
    opacity: 0.7,
  },
  seperator: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 0,
    height: 1,
  },
  controlTab: {
    height: '100%',
    width: '30%',
    backgroundColor: getColors().whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusTab: {
    height: '100%',
    width: '30%',
    backgroundColor: getColors().whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dataUsageTab: {
    height: '100%',
    width: '40%',
    backgroundColor: getColors().whiteColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtTab: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: wp('4.5%'),
    color: '#000000',
  },
  temperaturePopup: {
    width: wp('65%'),
    height: wp('75%'),
    margin: 0,
  },
  dotImage: {
    width: wp('4%'),
    height: wp('4%'),
    marginLeft: 10,
  },
  txtConnected: {
    fontFamily: Fonts.oxygenRegular,
    marginLeft: 10,
    fontSize: wp('5%'),
  },

  connectedView: {
    position: 'absolute',
    left: 10,
    top: 10,
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusView: {
    // position: 'absolute',
    // marginLeft: 15,
    // marginBottom: 10,
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
  },
  burnView: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    right: 10,
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsBtn: {
    //position: 'absolute',
    marginRight: 10,
    marginBottom: 10,
    width: 'auto',
    height: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnSettings: {
    width: wp('8.88%'),
    height: wp('8.88%'),
    marginBottom: 5,
  },
  sliderBackView: {
    width: '100%',
    height: wp('34%'),
    marginTop: 10,
  },
  disableView: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'white',
    opacity: 0.4,
  },
  controlTabTimeZoneBG: {
    width: 'auto',
    height: 'auto',
    justifyContent: 'center',
    marginHorizontal: 15,
    alignItems: 'center',
  },
  onTimeSetButton: {
    height: 50,
    width: 'auto',
    flex: 1,
    marginHorizontal: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellView: {
    width: 'auto',
    height: wp('18.05%'),
    marginTop: 16,
    marginHorizontal: 20,
    flexDirection: 'row',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 2.84,
    elevation: 2,
  },
  setPadding: {padding: 20},
  setPaddingZero: {padding: 0},

  blankViewStyle: {height: 40},
  tabbarUnderline: {width: '100%', height: 4, backgroundColor: '#E6E6E6'},
  btnAcceptStyle: {
    position: 'absolute',
    width: 80,
    height: 40,
    right: 10,
    bottom: -10,
  },
  btnCancelStyle: {
    width: 100,
    height: 40,
    marginTop: 10,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    backgroundColor: 'transparent',
  },
  txtLoaderDesc: {
    color: 'white',
    fontFamily: Fonts.oxygenBold,
    fontSize: 18,
  },
  txtPleaseWait: {
    color: 'white',
    fontFamily: Fonts.oxygenBold,
    fontSize: 20,
  },
  loaderBG: {
    width: '100%',
    height: 170,
    marginTop: -70,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  loaderBGBlack: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    opacity: 0.4,
  },
  loaderContainer: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  btnCloseStyle: {
    position: 'absolute',
    width: 80,
    height: 40,
    right: 10,
    bottom: -10,
  },
  setMarginTop: {marginTop: 20},
  setMarginTopTen: {marginTop: 10},
  imgWarning: {
    width: wp('7%'),
    height: wp('7%'),
  },
  setDirectionRow: {lexDirection: 'row'},
  setTrackHeight: {height: 8},
  setThumbStyle: {
    width: 22,
    height: 22,
    backgroundColor: getColors().redColor,
  },
  arrowContainer: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  txtOnOffContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  timePickerContainer: {
    flexDirection: 'row',
    width: '100%',
    height: wp('18.05%'),
    overflow: 'hidden',
  },
  txtTimerModeContainer: {
    backgroundColor: getColors().whiteColor,
    height: 'auto',
    flexDirection: 'column',
    marginBottom: 20,
  },
  setMarginLeft: {marginLeft: 20},
  txtRecircBG: {backgroundColor: 'transparent', height: 'auto'},
  switchStyle: {
    borderColor: getColors().redColor,
    borderWidth: 2,
    borderRadius: 15,
    marginTop: 5,
  },
  txtAutoContainer: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  setMarginRight: {marginRight: 10},
  setContentCenter: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  btnCancelBG: {
    backgroundColor: '#FFFFFF',
    borderColor: getColors().redColor,
    borderWidth: 1,
  },
  txtCancel: {
    color: 'white',
    fontFamily: Fonts.oxygenBold,
    fontSize: 22,
  },
  arrowStyle: {width: 20, height: 20},
  btnsContainerView: {flexDirection: 'row', marginTop: 20},
  passwordField: {marginTop: 10, marginHorizontal: -10},
  setTrashMargin: {marginTop: 5},
  setAuroHeight: {height: 'auto'},
  trashContainer: {
    width: 50,
    height: '100%',
    alignItems: 'flex-end',
  },
  slotListContainer: {
    marginHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  txtSwitchBack: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: wp('4.5%'),
    lineHeight: wp('5.6%'),
    paddingTop: 5,
    marginTop: 6,
  },
  txtIfYouSet: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: wp('4.5%'),
    lineHeight: wp('5.6%'),
    paddingTop: 5,
  },
  scaleImageStyle: {width: '100%', height: wp('10.3671%')},
  rangeBlockContainer: {
    position: 'absolute',
    flexDirection: 'row',
    bottom: 10,
    left: 20,
    right: 25,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rangeBlockBG: {
    height: 8,
    width: '100%',
    backgroundColor: getColors().maximumTrackTintColor,
  },
  sliderStyle: {
    position: 'absolute',
    bottom: 10,
    left: 20,
    right: 20,
  },

  ondemandSliderStyle: {
    marginHorizontal: 20,
    marginTop: 10,
  },
  bubbleView: {
    left: 20,
    right: 20,
    bottom: 50,
    height: 65,
    position: 'absolute',
  },
  txtSetTemperatureControl: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: wp('4.5%'),
    marginLeft: 20,
    color: '#000000',
  },
  buttonText: {
    fontFamily: Fonts.oxygenBold,
    fontSize: wp('4.5%'),
    color: '#000000',
  },
  txtMinTemp: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: hp('2%'),
    position: 'absolute',
    left: 20,
    bottom: 50,
  },
  txtMaxTemp: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: hp('2%'),
    position: 'absolute',
    right: 20,
    bottom: 50,
  },
  txtBubbleTemp: {
    fontFamily: Fonts.oxygenRegular,
    fontSize: wp('4%'),
  },
  cellInnerLeftView: {
    // width: '60%',
    flex: 1,
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },

  cellInnerRightView: {
    // width: '40%',
    width: 'auto',
    height: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  bgSettingsView: {
    width: '100%',
    height: 'auto',
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 65,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  settingsCell: {
    width: '100%',
    height: wp('11%'),
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingRight: 20,
    marginBottom: 15,
  },
  bubbleIcon: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    left: 0,
    top: 0,
  },
  btnText: {
    fontFamily: Fonts.oxygenBold,
    fontSize: wp('5%'),
    color: 'white',
  },
  txtDay: {
    fontSize: wp('3%'),
    color: 'grey',
    fontFamily: Fonts.oxygenBold,
    width: '100%',
    textAlign: 'center',
    marginTop: -20,
  },
  txtEvent: {
    fontSize: wp('3%'),
    color: 'grey',
    fontFamily: Fonts.oxygenBold,
    textAlign: 'right',
  },
  cancelPopup: {
    fontFamily: Fonts.oxygenBold,
    fontSize: wp('5%'),
    position: 'absolute',
    right: 100,
    bottom: -10,
    width: 90,
    height: 40,
  },
};

export default styles;
