export const SAVEHEATER_REQUEST = 'SAVEHEATER/SAVEHEATER_REQUEST';
export const SAVEHEATER_SUCCESS = 'SAVEHEATER/SAVEHEATER_SUCCESS';
export const SAVEHEATER_FAILURE = 'SAVEHEATER/SAVEHEATER_FAILURE';
