export const APP_VERSION_DATA_REQUEST = 'APP_VERSION_DATA_REQUEST';
export const APP_VERSION_DATA_SUCCESS = 'APP_VERSION_DATA_SUCCESS';
export const APP_VERSION_DATA_FAILURE = 'APP_VERSION_DATA_FAILURE';
