export const WARRANTY_REGISTER_REQUEST = 'WARRANTY_REGISTER/WARRANTY_REGISTER_REQUEST';
export const WARRANTY_REGISTER_SUCCESS = 'WARRANTY_REGISTER/WARRANTY_REGISTER_SUCCESS';
export const WARRANTY_REGISTER_FAILURE = 'WARRANTY_REGISTER/WARRANTY_REGISTER_FAILURE';
