export const SET_TIMEZONE_REQUEST = 'SETTIMEZONE/SET_TIMEZONE_REQUEST';
export const SET_TIMEZONE_SUCCESS = 'SETTIMEZONE/SET_TIMEZONE_SUCCESS';
export const SET_TIMEZONE_FAILURE = 'SETTIMEZONE/SET_TIMEZONE_FAILURE';
