export const RECIRCULATION_ONOFF_REQUEST = 'RECIRCULATION_ONOFF_REQUEST';
export const RECIRCULATION_ONOFF_SUCCESS = 'RECIRCULATION_ONOFF_SUCCESS';
export const RECIRCULATION_ONOFF_FAILURE = 'RECIRCULATION_ONOFF_FAILURE';
