export const GETINITIAL_REQUEST = 'GETINITIAL/GETINITIAL_REQUEST';
export const GETINITIAL_SUCCESS = 'GETINITIAL/GETINITIAL_SUCCESS';
export const GETINITIAL_FAILURE = 'GETINITIAL/GETINITIAL_FAILURE';
